### ISSUE TITLE
generator model predicts blank image

### ISSUE THREAD

**Issue by Sandeep9343** [Firdavs-coder/Aladdin-Persson-AI-Watermark-Destroy#5]
Hello,

I'm encountering a couple of issues while using this code for training on a custom dataset for watermark removal:

After 200 epochs, the 'D_fake' value reaches zero, which leads to the generation of a blank image in the evaluation folder.

When using the 'gen.pth.tar' model for prediction, it's producing a blank image.

Could you please provide some assistance with these problems?

**Comment by Firdavs-coder** [comment]
This code is written by looking on the YouTube video

**Comment by Sandeep9343** [comment]
i took the code from github 
still getting nan values while training
